name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]

env:
  
  AWS_REGION : "us-east-1" #Change to reflect your Region
  ROLE_ARN : ${{ Secrets.ARN_AWS }}
# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume:  ${{ env.ROLE_ARN }}
          role-session-name: GitHub_to_AWS
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: 
        run: |
          aws sts get-caller-identity
